### ISSUE TITLE
camera_csv

### ISSUE THREAD

**Issue by XingzhuoYan** [azamshoaib/DRFuser#1]
Hello, I want to run the code. But I can't find the required train_data_our.csv

parser.add_argument('--csv_file', type=str, default='//media/shoaib/work/dataset/dvs_data/train_data_our.csv', help='Path') in train.py

Could you please tell me where I can find this file? Thanks a lot.

**Comment by azamshoaib** [comment]
Hello @XingzhuoYan, Thank you for using our code.
First you need to download the data and prepare the data as described in the Readme.
The complete_data file will be the training data for that specified bag. But in order to use more bags data in the training data, you have to combine all the bags "complete_data" files. I hope that answer your query. If you have any further questions kindly do let me know. Thank you.
